# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true
[[main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    [main.params]
        icon = "user"

[[main]]
    identifier = "archives"
    name       = "Archives"
    url        = "/archives"
    [main.params]
        icon = "archives"

[[main]]
    identifier = "search"
    name       = "Search"
    url        = "/search"
    [main.params]
        icon = "search"

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://x.com/hukgteatime"

    [social.params]
        icon = "brand-twitter"
